GET http://localhost:5000/

###
POST http://localhost:5000/signup/
content-type : application/json

{
    "name":"isha gupta",
    "DOB":"19/09/1997",
    "username":"isha@gmail.com",
    "password":"0000"
}

###

POST http://localhost:5000/login/
content-type : application/json

{
    "username":"nick@gmail.com",
    "password":"9999"
}

###
GET http://localhost:5000/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvaGl0QGdtYWlsLmNvbSIsImlhdCI6MTU4OTUyMjY4MCwiZXhwIjoxNTg5NTI2MjgwfQ.jnD1qK72JEvM5qqWekosBLpSiDDGhvnqoWMV0OkdqXY


###
POST http://localhost:5000/addImage
Content-Type: application/json

{
    "username":"golu@gmail.com",
    "filename":"wp1880219-the-seven-deadly-sins-wallpapers.jpg",
    "desc":"this is amazing"
}

###
POST http://localhost:5000/delete 
Content-Type: application/json

{
    "username":"nick@gmail.com",
    "id":"5ebd07dce96ca323aa13d82c"
}